const axios = require("axios");

module.exports.config = {
  name: "sony",
  version: "1.0.2",
  hasPermssion: 0,
  credits: "Aman",
  description: "Gemini chatbot with sony/bot trigger and reply context",
  commandCategory: "no prefix",
  usages: "no prefix",
  cooldowns: 2
};

module.exports.handleEvent = async function ({ api, event }) {
  const { threadID, messageID, body, senderID, messageReply } = event;

  if (!body || senderID == api.getCurrentUserID()) return;

  const lowerBody = body.toLowerCase();

  // Trigger words check
  const hasTriggerWords = lowerBody.includes("sony") || lowerBody.includes("SONY");

  // Check: reply to bot + message actually generated by sony command
  const isReplyToSonyBot =
    messageReply &&
    messageReply.senderID == api.getCurrentUserID() &&
    messageReply.body &&
    messageReply.body.includes("★᭄𝐎𝐰𝐧𝐞𝐫 𝐀 𝐊"); // unique tag Sony msg ka

  if (hasTriggerWords || isReplyToSonyBot) {
    try {
      // Reaction 🥰
      api.setMessageReaction("🥰", messageID, (err) => {}, true);

      // Sender name fetch
      const userInfo = await api.getUserInfo(senderID);
      const userName = userInfo[senderID]?.name || "User";

      let finalMessage = body;

      // If replying to Sony bot's message, include context
      if (isReplyToSonyBot && messageReply) {
        const repliedMessage = messageReply.body || "";
        finalMessage = `Previous message: ${repliedMessage} | User's reply: ${body}`;
      }

      // API call with context
      const res = await axios.post("https://api-h92t.onrender.com/gemini", {
        message: finalMessage
      });

      if (!res.data || !res.data.reply) {
        return api.sendMessage("⚠️ sony ne sahi reply nahi diya.", threadID, messageID);
      }

      // Final message format with decorative headers
      const finalMsg = `
✨ ${userName} ✨
✿━━━━━━━━⊱🌺⊰━━━━━━━━✿

${res.data.reply}
✿━━━━━━━━⊱🌺⊰━━━━━━━━✿
*★᭄𝐎𝐰𝐧𝐞𝐫 𝐀 𝐊 ⚔️⏤͟͟͞͞★*
`;

      return api.sendMessage(finalMsg, threadID, messageID);
    } catch (error) {
      console.error("Gemini API error:", error.message);

      // Multiple funny/romantic error messages
      const errorMessages = [
        "Tum online ho aur reply nahi dete, dil todna bhi ek art hai kya 😏",
        "Mujhe tumse ek complaint hai... tum cute itne kyu ho 🥺💖",
        "Suno ji, tumhari yaad aati hai jaise mobile ko charging ki zarurat hoti hai ⚡❤️",
        "Aaj mausam bada suhana hai, tum mil jao to aur bhi deewana hai 🌸",
        "Khud pe itna na karo tum ghamand, tumhe dekh ke to dil ka signal ho gaya jammed 😜",
        "Life me tension mat lo, warna tumhare dimples bhi chhup jayenge 😉",
        "Pizza aur tum dono favourite ho, farq bas itna hai pizza khane ko mil jata hai 🍕❤️",
        "Dil garden-garden ho jata hai jab tum online aate ho 🌹",
        "Tumhari smile meri weakness hai, please jyada mat hansa karo ☺️",
        "Abhi to zindagi me bahut goals hai, par sabse bada goal tum ho 😘",
        "Tera naam WhatsApp pe aata hai to lagta hai life mast chal rahi hai 🤩",
        "Tumhare bina ye duniya adhoori si lagti hai, jaise chai bina biscuit 😆☕",
        "Tum smart ho ya main hi tumhe dekh ke pagal ho gayi hoon 🤭",
        "Tum meri life ka wo chapter ho jisme sirf smile hi smile likha hai 😍",
        "Chhodo na ye duniya walo ki baatein, aao hum dono ek chhoti si duniya bana le 💕",
        "Sad mat ho yaar, warna tumhari ankho ki chamak kam ho jayegi 🌟",
        "Tumhari baaton me wo magic hai, jo har boring din ko special bana deta hai ✨",
        "Dil chahta hai tumhe bas roz pareshaan karu aur tum hamesha hans ke reply do 😋",
        "Tum meri coffee ho yaad aati ho subah-subah aur din acha kar deti ho ☕❤️",
        "Mujhe tumse ek problem hai… tumhe bhool hi nahi paati 😍"
      ];

      const randomMsg = errorMessages[Math.floor(Math.random() * errorMessages.length)];

      return api.sendMessage(randomMsg, threadID, messageID);
    }
  }
};

module.exports.run = async function () {
  return;
};
